minimalDMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ocr.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ocr/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.archive, name="archive"),
    path('archive/<int:id>', views.edit, name="edit"),
    path('inbox/', views.inbox, name="inbox"),
    path('scaninput/', views.scaninput, name="scaninput"),
    path('inbox_scaninput/', views.inbox_scaninput, name="inbox_scaninput"),
    path('tags/', views.tags, name="tags"),
    path('doctypes/', views.doctypes, name="doctypes"),
    path('persons/', views.persons, name="persons"),
    path('download/<filefolder>/<filename>', views.download, name='download'),
    path('download_inbox/<file>', views.download_inbox, name='download_inbox'),
]

ocr/models.py
from django.db import models
from uuid import uuid4


class Status(models.Model):
    status = models.CharField(max_length=30)

    def __str__(self):
        return self.status


class Doctype(models.Model):
    doctype = models.CharField(max_length=30)

    def __str__(self):
        return self.doctype

    @property
    def get_number_of_items(self):
        number_of_items = len(Document.objects.filter(doctype=self.id))

        return number_of_items


class Person(models.Model):
    person = models.CharField(max_length=50)

    def __str__(self):
        return self.person
    
    @property
    def get_number_of_items(self):
        number_of_items = len(Document.objects.filter(person=self.id))

        return number_of_items


class Tag(models.Model):
    tag = models.CharField(max_length=30)

    def __str__(self):
        return self.tag

    @property
    def get_number_of_items(self):
        number_of_items = len(Document.objects.filter(tags=self.id))

        return number_of_items


class Document(models.Model):
    name = models.CharField(max_length=260)
    status = models.ForeignKey(Status, on_delete=models.DO_NOTHING)
    doctype = models.ForeignKey(Doctype, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    date = models.DateTimeField(auto_now=True, null=True, blank=True)
    docdate = models.DateField()
    resubmission = models.DateField(null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to="data/" + str(uuid4()))
    filename = models.CharField(max_length=260, null=True, blank=True)
    filefolder = models.CharField(max_length=36, null=True, blank=True)
    notes = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name


class Version(models.Model):
    docid = models.IntegerField()
    version = models.IntegerField(blank=True, null=True)
    date = models.DateTimeField()
    file = models.FileField()
    filename = models.CharField(max_length=260, null=True, blank=True)
    filefolder = models.CharField(max_length=36, null=True, blank=True)

ocr/views.py
from django.shortcuts import redirect, render
import pytesseract
from pdf2image import convert_from_path
from pypdf import PdfReader, PdfWriter
from .forms import DocumentForm, DocumentFormEdit, DocumentFormInput, TagForm, DoctypeForm, PersonForm
from .models import Document, Version, Tag, Status, Doctype, Person
from django.http import FileResponse
from django.conf import settings
import os
from io import BytesIO
import datetime
import shutil
from uuid import uuid4
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from threading import Thread


class OCRThread(Thread):
    def __init__(self, instance, request):
        super(OCRThread, self).__init__()
        self.instance = instance
        self.request = request

    def run(self):
        messages.error(self.request, f'<i class="bi bi-exclamation-triangle-fill"></i> <b>{self.instance.name}</b> wird im Hintergrund verarbeitet.')
        self.instance.filename = self.instance.file.name.split('/')[2]
        self.instance.filefolder = self.instance.file.name.split('/')[1]
        text, error = ocr_scan(self.instance.file.path)
        self.instance.text = text
        if not error:
            self.instance.save()
        else:
            self.instance.delete()
            # fail silently at the moment
            # messages.error(self.request, f'<i class="bi bi-exclamation-triangle-fill"></i> Beim Speichern von <b>{self.instance.name}</b> ist ein Fehler aufgetreten. Es handelt sich nicht um eine lesbare PDF-Datei.')


def inbox(request):
    f = DocumentForm()

    inbox_files = get_inbox_files()  

    if request.method == 'POST':
        f = DocumentForm(request.POST, request.FILES)
        if f.is_valid():
            f.save()
            instance = f.save(commit=False)
            thread = OCRThread(instance, request)
            thread.start()
            return redirect('archive')

    return render(request, 'inbox.html', {'form': f, 'inbox_files': inbox_files})


def scaninput(request):
    inbox_files = get_inbox_files()

    return render(request, 'scaninput.html', {'inbox_files': inbox_files})


def inbox_scaninput(request):
    f = DocumentFormInput()

    if request.POST.get('inbox_file'):
        file = request.POST.get('inbox_file')

    if request.POST.get('save'):
        f = DocumentFormInput(request.POST)
        if f.is_valid():
            f.save()
            instance = f.save(commit=False)
            uuid_dir = str(uuid4())
            input_path = os.path.join(settings.MEDIA_ROOT, 'inbox', request.POST.get('save'))
            dest_path = os.path.join(settings.MEDIA_ROOT, 'data', uuid_dir)
            text, error = ocr_scan(input_path)
            instance.text = text
            os.mkdir(dest_path)
            shutil.move(input_path, dest_path)
            instance.file = 'data/' + request.POST.get('save')
            instance.filename = request.POST.get('save')
            instance.filefolder = uuid_dir
            if not error:
                instance.save()
                return redirect('archive')
            else:
                instance.delete()
                messages.error(request, f'<i class="bi bi-exclamation-triangle-fill"></i> Beim Speichern von <b>{instance.name}</b> ist ein Fehler aufgetreten. Es handelt sich nicht um eine lesbare PDF-Datei.')

    return render(request, 'inbox_scaninput.html', {'form': f, 'file': file, })


def edit(request, id):
    obj = Document.objects.get(id=id)
    tags = Tag.objects.all()
    oldfile = obj.file
    try:
        versions = Version.objects.filter(docid=id)
        v = Version.objects.filter(docid=id).last()
    except Exception:
        v = 0
    else:
        if v is not None:
            v = v.version
        else:
            v = 0

    if request.method == 'POST':
        f = DocumentFormEdit(request.POST, request.FILES, instance=obj)
        if f.is_valid():
            # check if new version and save old file in Version model
            if 'file' in f.changed_data:
                Version.objects.create(
                    docid=id,
                    version=v + 1,
                    date=obj.date,
                    file=oldfile,
                    filefolder=obj.filefolder,
                    filename=obj.filename,
                )
            f.save()
            if 'file' in f.changed_data:
                instance = f.save(commit=False)
                instance.filename = instance.file.name.split('/')[2]
                instance.filefolder = instance.file.name.split('/')[1]
                text, error = ocr_scan(instance.file.path)
                instance.text = text
                if not error:
                    instance.save()
                else:
                    messages.error(request, f'<i class="bi bi-exclamation-triangle-fill"></i> <small>Beim Speichern von einer neuen Dateiversion von <b>{instance.name}</b> ist ein Fehler aufgetreten. Es handelt sich nicht um eine lesbare PDF-Datei.</small>')
        current_status = ""
        if request.GET.get('current_status') != "None":
            current_status = request.GET.get('current_status')
        if request.GET.get('current_doctype') != "None":
            current_doctype = request.GET.get('current_doctype')
        if request.GET.get('search_text') != "None":
            search_text = request.GET.get('search_text')
        if request.GET.get('person') != "None":
            person = request.GET.get('person')
        checked_tags = ""
        for i in tags:
            if request.GET.get(i.tag) == "1":
                checked_tags += f"&{i.tag}=1"
        return redirect(f"/?status={current_status}&search={search_text}&doctype={current_doctype}&person={person}&submit=submit{checked_tags}")

    f = DocumentFormEdit(instance=obj)
    return render(request, 'edit.html', {
        'form': f,
        'date': obj.date,
        'filename': obj.filename,
        'versions': versions,
        }
    )


def ocr_scan(filepath):
    error = None
    text = ""
    try:
        # get text from pdf
        reader = PdfReader(filepath)
        for page in reader.pages:
            text += page.extract_text()

        # always add complete text from images to text variable as well
        # if no text in pdf: convert to image and then to searchable pdf
        images = convert_from_path(filepath, dpi=300, fmt='tiff')
        writer = PdfWriter()
        if text == "":
            for image in images:
                page = pytesseract.image_to_pdf_or_hocr(image, lang="deu", extension='pdf')
                pdf = PdfReader(BytesIO(page))
                text += pytesseract.image_to_string(image, lang="deu")
                writer.add_page(pdf.pages[0])
            # export pdf to same filename as searchable pdf if only image
            with open(filepath, 'wb') as f:
                writer.write(f)
        else:
            for image in images:
                text += pytesseract.image_to_string(image, lang="deu")
    except Exception:
        error = True

    return text, error


def archive(request):
    tags = Tag.objects.all()
    status_options = Status.objects.all()
    doctypes = Doctype.objects.all()
    persons = Person.objects.all()
    if request.GET.get('delete_search'):
        return redirect('archive')
    if request.GET.get('form_submitted'):
        search_strings = request.GET.get('search').split(" ")
        for search_string in search_strings:
            docs = (
                Document.objects.filter(text__icontains=search_string) | 
                Document.objects.filter(name__icontains=search_string) | 
                Document.objects.filter(filename__icontains=search_string) | 
                Document.objects.filter(notes__icontains=search_string)
            ).order_by('-docdate')
        checked_tags = []
        for i in tags:
            if request.GET.get(i.tag) == "1":
                docs = docs.filter(tags__tag__icontains=i.tag)
                checked_tags.append(i)
        current_status = ""
        if request.GET.get('status'):
            current_status = request.GET.get('status')
            docs = docs.filter(status__status=current_status)
        current_doctype = ""
        if request.GET.get('doctype'):
            current_doctype = request.GET.get('doctype')
            docs = docs.filter(doctype__doctype=current_doctype)
        current_person = ""
        if request.GET.get('person'):
            current_person = request.GET.get('person')
            docs = docs.filter(person__person=current_person)
        docs = docs[:100]
        hundred_or_more = None
        if len(docs) == 100:
            hundred_or_more = True
        return render(request, 'archive.html', {
            'docs': docs,
            'tags': tags,
            'status_options': status_options,
            'current_status': current_status,
            'current_doctype': current_doctype,
            'current_person': current_person,
            'doctypes': doctypes,
            'persons': persons,
            'search_text': request.GET.get('search'),
            'checked_tags': checked_tags,
            'hundred_or_more': hundred_or_more,
            }
        )
    else:
        docs = Document.objects.all().order_by('-docdate')[:100]
        hundred_or_more = None
        if len(docs) == 100:
            hundred_or_more = True
        return render(request, 'archive.html', {
            'docs': docs,
            'tags': tags,
            'status_options': status_options,
            'doctypes': doctypes,
            'persons': persons,
            'hundred_or_more': hundred_or_more,
            }
        )


def get_inbox_files():
    # Define the directory path
    directory_path = settings.MEDIA_ROOT + '/inbox'

    # Initialize a list to store file information
    file_list = []

    # Check if the directory exists
    if os.path.exists(directory_path) and os.path.isdir(directory_path):
        # List all files in the directory

ocr/templates/archive.html
{% extends 'base.html' %}  
{% block content %}
{% load i18n %}
<style>
  .mycol {
    columns: 4;
  }
</style>

<h3><i class="bi bi-archive-fill"> </i>{% trans "Archive" %}</h3>

<label for="search" class="form-label">{% trans "Search for text in PDF files, remark, file name and notes:" %}</label>
<div id="upper">
<form>
  <div class="row">
    <div class="col">
      <input class="form-control form-control-lg" id="search" name="search" value="{{ search_text }}">
    </div>
    <div class="col-auto">
      <button type="submit" name="form_submitted" value="1" class="btn btn-lg btn-primary"><i class="bi bi-search"></i>&nbsp;{% trans "Search" %}</button>
      <button type="submit" name="delete_search" value="delete_search" class="btn btn-lg btn-secondary" style="height: 48px;"><i class="bi bi-x-circle"></i></button>
    </div>
  </div>
  <nav>
    <div class="nav nav-tabs mt-2" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true" onclick="calculateHeight();"><i class="bi bi-tags-fill"></i> Tags</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-status" type="button" role="tab" aria-controls="nav-status" aria-selected="false" onclick="calculateHeight();"><i class="bi bi-stoplights-fill"></i> Status</button>
      <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-doctype" type="button" role="tab" aria-controls="nav-doctype" aria-selected="false" onclick="calculateHeight();"><i class="bi bi-file-earmark-text-fill"></i> {% trans "Document type" %}</button>
      <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-person" type="button" role="tab" aria-controls="nav-person" aria-selected="false" onclick="calculateHeight();"><i class="bi bi-person-vcard-fill"></i> Person</button>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div class="mt-2">
      {% for tag in tags %}
        <!-- <div class="col-3 mt-2"> -->
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="checkbox" name="{{ tag }}" value="1" id="{{ tag }}" onchange="this.form.submit()"
          {% if tag in checked_tags %}
          checked
          {% endif %}
          >
          <input type="hidden" name="form_submitted" value="1">
          <label for="{{ tag }}" class="badge bg-secondary" style="margin-top: 2px;">
            {{ tag }}
          </label>
        </div>
      {% endfor %}
      </div>
    </div>
    <div class="tab-pane fade" id="nav-status" role="tabpanel" aria-labelledby="nav-status-tab">
      <div class="col mt-2 ms-2">
        <input class="form-check-input" type="radio" name="status" value="" id="None" {% if not stat.status %}checked{% endif %}>
        <label class="form-check-label" for="None">{% trans "All" %}</label>
      </div>
      {% for stat in status_options %}
        <div class="col mt-2 ms-2">
          <input class="form-check-input" type="radio" name="status" value="{{ stat }}" id="{{ stat }}" {% if stat.status == current_status %}checked{% endif %}>
          <label class="form-check-label" for="{{ stat }}">{{ stat }}</label>
        </div>
      {% endfor %}
    </div>
    <div class="tab-pane fade" id="nav-doctype" role="tabpanel" aria-labelledby="nav-doctype-tab">
      <div class="col mt-2 ms-2">
        <select class="form-select" name="doctype" aria-label="Dokumentenart">
          <option value="" selected>Alle</option>
            {% for doctype in doctypes %}
              <option value="{{ doctype }}" {% if doctype.doctype == current_doctype %}selected{% endif %}>{{ doctype }}</option>
            {% endfor %}
        </select>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-person" role="tabpanel" aria-labelledby="nav-person-tab">
      <div class="col mt-2 ms-2">
        <select class="form-select" name="person" aria-label="Person">
          <option value="" selected>---</option>
            {% for person in persons %}
              <option value="{{ person }}" {% if person.person == current_person %}selected{% endif %}>{{ person }}</option>
            {% endfor %}
        </select>
      </div>
    </div>
  </div>
</form>
</div>

<div class="row" id="lower" style="overflow: scroll;">
  <div class="col">
    <table class="table">
      <thead>
        <tr>
          <th scope="col" style="width: 20vw;">{% trans "Remark" %}</th>
          <th scope="col">Tags</th>
          <th scope="col">Status</th>
          <th scope="col">{% trans "Date" %}</th>
          <th scope="col">{% trans "Type" %}</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for doc in docs %}
          <!-- <form action="{% url 'edit' doc.id %}"> -->
          <!-- <form action="/archive/{{ doc.id }}?current_status={{ current_status }}"> -->
            {% if forloop.counter|divisibleby:2 %}
            <tr class="table-secondary">
            {% else %}
            <tr class="table-light">
            {% endif %}
              <td rowspan="2" class="align-middle" style="width: 20vw;">{{ doc.name }} {% if doc.notes %} <i class="bi bi-sticky-fill" style="color: rgb(46, 148, 97);" data-bs-html="true" data-bs-toggle="popover" data-bs-title="Notiz" data-bs-content="{{ doc.notes|linebreaksbr }}"></i>{% endif %}</td>
              <td>
                {% for tag in doc.tags.all %}  
                <span class="badge bg-secondary mt-1">{{ tag }}</span>
                {% endfor %}  
              </td>
              {% if doc.status.id == 2 %}
                <td><div style="color: brown;"><i class="bi bi-circle"></i> {{ doc.status }}</div></td>
              {% elif doc.status.id == 1 %}
                <td><div style="color: rgb(22, 131, 87);"><i class="bi bi-check-circle"></i> {{ doc.status }}</div></td>
              {% elif doc.status.id == 3 %}
                <td><div style="color: rgb(227, 140, 0);"><i class="bi bi-alarm-fill"></i> {{ doc.status }}</div></td>
              {% else %}
                <td>{{ doc.status }}</td>
              {% endif %}
              <td>{{ doc.docdate|date:"d.m.y" }}</td>
              <td>{{ doc.doctype }}</td>
              <td rowspan="2" class="align-middle"><div class="text-end"><a href="/archive/{{ doc.id }}?current_status={{ current_status }}&current_doctype={{ current_doctype }}&search_text={{ search_text }}&person={{ current_person }}{% for tag in checked_tags %}&{{ tag }}=1{% endfor %}" type="submit" class="btn btn-secondary btn-sm d-flex align-items-center" style="height: 32px; width: 32px;"><i class="bi bi-pencil-fill"></i></a></div></td>
            </tr>
            {% if forloop.counter|divisibleby:2 %}
            <tr class="table-secondary">
            {% else %}
            <tr class="table-light">
            {% endif %}
              <td colspan="4"><i class="bi bi-file-text"> </i><a class="text-break badge custom-badge" href="{% url 'download' doc.filefolder doc.filename %}">{{ doc.filename }}</a>
              <small>(Erstellt: {{ doc.date|date:"d.m.y, H:i" }})</small> 
              {% if doc.person %}
                &nbsp; &middot; &nbsp; <i class="bi bi-person-vcard-fill"></i> {{ doc.person }}
              {% endif %}
              </td>
            </tr>
          <!-- </form> -->
        {% endfor %}
      </tbody>
    </table>
    {% if hundred_or_more %}
      <div class="text-center">
        <p><em>{% trans "The first 100 entries are shown. Customize your search to show more entries." %}</em></p>
      </div>
    {% endif %}
  </div>
</div>

<script>
  const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
  const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))

  function calculateHeight() {
    // Get the viewport height
    var viewportHeight = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;

    // Get the height of the upper div
    var upperDivHeight = document.getElementById("upper").clientHeight;

    // Calculate the height of the lower div
    var lowerDivHeight = viewportHeight - upperDivHeight - 245;

    // Set the height of the lower div
    document.getElementById("lower").style.height = lowerDivHeight + "px";
  }

  // Add event listener for window resize
  window.addEventListener('resize', function () {
    calculateHeight();
  });
  
  // call function on page load
  calculateHeight();
</script>

{% endblock content %}

ocr/templates/edit.html
{% extends 'base.html' %}  
{% block content %}
<style>
  .mycol {
  columns: 4;
}
</style>


<h3>Eigenschaften bearbeiten</h3>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="col">
      <p><label for="id_name"><strong>Name/Bemerkung:</strong></label> {{ form.name }}</p>
    </div>
  </div>
  
  <div class="row">
    <div class="col">
      <p><label for="id_status"><strong>Status:</strong></label> {{ form.status }}</p>
    </div>

    <div class="col">
      <p><label for="id_doctype"><strong>Dokumentenart:</strong></label> {{ form.doctype }}</p>
    </div>

    <div class="col">
      <p><label for="id_docdate"><strong>Datum:</strong></label> {{ form.docdate }}</p>
    </div>
  </div>

  <div class="row" style="display: none;" id="id_resubmission">
    <div class="col-4">
      <p><label for="id_docdate" ><strong>Wiedervorlagedatum:</strong></label> {{ form.resubmission }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p><label for="id_person"><strong>Person (optional):</strong></label> {{ form.person }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <label><strong>Tags:</strong></label>{{ form.tags }}
    </div>
  </div>
 
  <div class="row mt-3">
    <div class="col">
      <strong>Aktuelle Datei: </strong><i class="bi bi-file-text"> </i><a class="text-break badge custom-badge" href="{% url 'download' form.instance.filefolder form.instance.filename %}">{{ filename }}</a><br>
      vom {{ date|date:"d.m.y, H:i" }}
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <strong>Versionen:</strong><br>
      {% if versions %}
        {% for version in versions %}
          <a href="{% url 'download' version.filefolder version.filename %}">{{ version.filename }}</a> - Version {{ version.version }} - {{ version.date|date:"d.m.y, H:i" }}<br>
        {% endfor %}
      {% else %}
        - keine -
      {% endif %}
    </div>
  </div>

  <div class="row mt-3 mb-4">
    <div class="col">
      <label><strong>Neue Version hochladen: </strong>:</label> {{ form.file }}
    </div>
  </div>

  <div class="row mt-3 mb-4">
    <div class="col">
      <label><strong>Notizen: </strong></label> {{ form.notes }}
    </div>
  </div>

  <button type="submit" onclick="spinner()" class="btn btn-primary">Speichern</button>
</form>

  <div class="spinner-border" style="display: none;">
    <span class="visually-hidden">Loading...</span>
  </div>

  <script>
    // Get references to the select and input elements
    const id_status = document.getElementById('id_status');
    const id_resubmission = document.getElementById('id_resubmission');
  
    // Add an event listener to the select element
    id_status.addEventListener('change', function () {
        if (id_status.value === '3') {
            // Show the "resubmission" row if "resubmission" is selected
            id_resubmission.style.display = 'block';
        } else {
            // Hide the row for other options
            id_resubmission.style.display = 'none';
        }
    });

    // Check the initial value of the select element on page load
    if (id_status.value === '3') {
          // Show the "resubmission" row if "resubmission" is initially selected
          id_resubmission.style.display = 'block';
      }
  </script>


{% endblock content %}

ocr/templates/inbox.html
{% extends 'base.html' %}  
{% block content %}
<style>
  .mycol {
  columns: 4;
}
</style>

<h3><i class="bi bi-mailbox2">&ensp;</i>Inbox</h3>

<form method="POST" enctype="multipart/form-data" id="inbox_form">
  {% csrf_token %}
  <!-- {{ form.as_p }} -->
  <div class="row">
    <div class="col">
      <p><label for="id_name"><strong>Name/Bemerkung:</strong></label> {{ form.name }}</p>
    </div>
  </div>
  
  <div class="row">
    <div class="col">
      <p><label for="id_status"><strong>Status:</strong></label> {{ form.status }}</p>
    </div>

    <div class="col">
      <p><label for="id_doctype"><strong>Dokumentenart:</strong></label> {{ form.doctype }}</p>
    </div>

    <div class="col">
      <p><label for="id_docdate"><strong>Datum:</strong></label> {{ form.docdate }}</p>
    </div>

  </div>
  
  <div class="row">
    <div class="col">
      <p><label for="id_person"><strong>Person (optional):</strong></label> {{ form.person }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <label><strong>Tags (optional):</strong></label>{{ form.tags }}
    </div>
  </div>


  <div class="row mt-3 mb-4">
    <div class="col">
      <label><strong>Datei hochladen:</strong></label> {{ form.file }}
    </div>
  </div>

  <div class="row mt-3 mb-4">
    <div class="col">
      <label><strong>Notizen: </strong></label> {{ form.notes }}
    </div>
  </div>
  <button type="submit" onclick="spinner()" class="btn btn-primary">Speichern</button>
</form>

<div class="spinner" style="display: none;">
  <div class="spinner-border mb-2" style="display: block;">
    <span class="visually-hidden">Loading...</span>
  </div>
  <i>Führe Texterkennung durch...</i>
</div>


<script>
  function spinner() {
    if (validateForm()) {
      document.getElementsByClassName("spinner")[0].style.display = "block";
    }
  };

  function hide_spinner() {
      document.getElementsByClassName("spinner")[0].style.display = "none";
  };

  function validateForm() {
          var form = document.getElementById('inbox_form');
          return form.checkValidity();
  };
</script> 

{% endblock content %}

ocr/templates/inbox_scaninput.html
{% extends 'base.html' %}
{% block content %}
<style>
  .mycol {
  columns: 4;
}
</style>

<h3><i class="bi bi-mailbox2">&ensp;</i>Inbox Scaninput</h3>

<form method="POST" id="inbox_form">
  {% csrf_token %}
  <p><strong>zu archivierende Datei: </strong><a class="text-break badge bg-success me-2" href="{% url 'download_inbox' file %}">{{ file }}</a></p>
  <!-- {{ form.as_p }} -->
  <div class="row">
    <div class="col">
      <p><label for="id_name"><strong>Name/Bemerkung</strong>:</label> {{ form.name }}</p>
    </div>
  </div>
  
  <div class="row">
    <div class="col">
      <p><label for="id_status"><strong>Status</strong>:</label> {{ form.status }}</p>
    </div>

    <div class="col">
      <p><label for="id_doctype"><strong>Dokumentenart</strong>:</label> {{ form.doctype }}</p>
    </div>

    <div class="col">
      <p><label for="id_docdate"><strong>Datum</strong>:</label> {{ form.docdate }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p><label for="id_person"><strong>Person (optional):</strong></label> {{ form.person }}</p>
    </div>

  </div>
  <div class="row">
    <div class="col">
      <label><strong>Tags:</strong></label>{{ form.tags }}
    </div>
  </div>
 
  <div class="row mt-3 mb-4">
    <div class="col">
      <label><strong>Notizen: </strong>:</label> {{ form.notes }}
    </div>
  </div>
  <button type="submit" name="save" value="{{ file }}" onclick="spinner()" class="btn btn-primary">Speichern</button>
</form>

<div class="spinner" style="display: none;">
  <div class="spinner-border mb-2" style="display: block;">
    <span class="visually-hidden">Loading...</span>
  </div>
  <i>Führe Texterkennung durch...</i>
</div>


<script>
  function spinner() {
    if (validateForm()) {
      document.getElementsByClassName("spinner")[0].style.display = "block";
    }
  };

  function hide_spinner() {
      document.getElementsByClassName("spinner")[0].style.display = "none";
  };

  function validateForm() {
          var form = document.getElementById('inbox_form');
          return form.checkValidity();
  };
</script> 

{% endblock content %}

ocr/templates/scaninput.html
{% extends 'base.html' %}  
{% block content %}
<style>
  .mycol {
  columns: 4;
}
</style>

<h3><i class="bi bi-box-arrow-in-right"></i> Scaninput</h3>
<form method="post" action="{% url 'inbox_scaninput' %}">
  {% csrf_token %}
  <ul class="list-group">
  {% for file in inbox_files %}
    <li class="list-group-item"><a class="text-break badge bg-success me-2" href="{% url 'download_inbox' file.filename %}">{{ file.filename }}</a> {{ file.creation_time }} 
      <button class="btn btn-secondary btn-sm ms-2" name="inbox_file" value="{{ file.filename }}"><i class="bi bi-stack"></i> Archivieren</button>
    </li>
  {% endfor %}
  </ul>
</form>


{% endblock content %}